### ISSUE TITLE
Update the output logs generated by LWC_TB 

### ISSUE THREAD

**Issue by Grimgoodbye** [GMUCERG/LWC#14]
Requested output:

CSV ADLEN, MSGLEN, Cycles

This allows the user to verify their formulas.

Additionally, another log should generate the message that are currently reports.

**Comment by shrub77** [comment]
Currently, the testbench generates a `log.txt` with events related to simulation. Do we want timing calculations to be outputted to this file, or do we want to create a new file just for timing results? Here is a sample of the current log file:

```
[Log] == Verifying msg ID #1 with key ID #1 for DEC
[Log]     Expected: 43000010 Received: 43000010 Matched!
[Log]     Expected: 119424C8 Received: 119424C8 Matched!
[Log]     Expected: 96F4CF4A Received: 96F4CF4A Matched!
[Log]     Expected: BD9A013A Received: BD9A013A Matched!
[Log]     Expected: C573BCF2 Received: C573BCF2 Matched!
[Log]     Expected: E0000000 Received: E0000000 Matched!
[Log] == Verifying msg ID #2 with key ID #1 for DEC
[Log]     Expected: 43000010 Received: 43000010 Matched!
[Log]     Expected: 5C66DE9E Received: 5C66DE9E Matched!
[Log]     Expected: 092C20A1 Received: 092C20A1 Matched!
[Log]     Expected: 38A8C5AB Received: 38A8C5AB Matched!
[Log]     Expected: F1005B05 Received: F1005B05 Matched!
[Log]     Expected: E0000000 Received: E0000000 Matched!
[Log] Done
```

In my opinion, it should be separated to avoid adding to the visual clutter in log.txt which could cause confusion.

**Comment by Grimgoodbye** [comment]
In my opinion we should use a different log to reduce the message clutter. Kamyar what are your thoughts?

**Comment by Grimgoodbye** [comment]
I didn't read you last line. I guess we agree.

**Comment by Grimgoodbye** [comment]
Execution in cycles and latency to an output log
