### ISSUE TITLE
Ensure the prepare source update support all versions of LWC rnd 2 candidates

### ISSUE THREAD

**Issue by Grimgoodbye** [GMUCERG/LWC#15]
Currently the PR is up does not support romulas and another algorithm. Support them.

**Comment by kammoh** [comment]
`cryptotvgen` #20 automatically builds references implementation of all round 2 AEAD and hash LWC variants from SUPRCOP, including 6 variants of `romulas` AEAD.

**Comment by kammoh** [comment]
#20 should address this.
