### ISSUE TITLE
-novopt deprecated, causes simulation error in modelsim.tcl

### ISSUE THREAD

**Issue by shrub77** [GMUCERG/LWC#2]
when running the modelsim.tcl script using the latest version of vsim (vsim-12110), the follow error pops up:

`Error (suppressible): (vsim-12110) The -novopt option has no effect on this product. -novopt option is now deprecated and will be removed in future releases.`

Consider removing  `-novopt` as it has been deprecated for some time now, or using  `-voptarguments=+acc`

**Comment by jpkaps** [comment]
Rishub, thanks for this comment. We will remove the -novopt option in version 1.0.3. We will not replace it with -voptarguments=+acc as this leads so an error on older versions of Modelsim.
