### ISSUE TITLE
Set up private / public gitter rooms

### ISSUE THREAD

**Issue by kammoh** [GMUCERG/LWC#21]
I'd suggest we set up [gitter](https://gitter.im/) rooms for faster and more convenient communication between developers as well as providing timely support to the users of this repository. 

1. Public room: provide help and support to the users of the LWC package 
2. Private room: discussions among developers 

Needs to be done by an owner (@jpkaps) I guess. Any thoughts?

**Comment by ekawat** [comment]
Agreed.

-ice

**Comment by shrub77** [comment]
A mailing list may be better due to the low traffic nature of this project
