### ISSUE TITLE
msg_auth_ready is set when the controller is not ready to process it.

### ISSUE THREAD

**Issue by Grimgoodbye** [GMUCERG/LWC#27]
When performing decryption the msg_auth_ready flag is set to 1 but the CryptoCore says the message is valid at in the same cycle as the last TAG is validated the PostProcessor(might be another component) cannot handle this.

Reason why this is not ideal is that it leads to a difference in the cycles between encrypt and decrypt by 1 cycle.

Suggested fix:
Allow the LWC to process msg_auth in the same cycle as the the last tag message.

**Comment by ekawat** [comment]
Do we have a test case for this?

**Comment by kammoh** [comment]
Can we close this since #35 is merged in?
